---
- name: Get vcenter info
  vmware_about_info:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
  register: vcenter_info

- name: Create {{ vcenter.role_prefix }}-vcenter-level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: "{{ vcenter.role_prefix }}-vcenter_level"
    local_privilege_ids: "{{ vcenter_level }}"
    state: present

- name: Create {{ vcenter.role_prefix }}-cluster-level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: "{{ vcenter.role_prefix }}-cluster_level"
    local_privilege_ids: "{{ cluster_level }}"
    state: present

- name: Create {{ vcenter.role_prefix }}-datastore_level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: "{{ vcenter.role_prefix }}-datastore_level"
    local_privilege_ids: "{{ datastore_level }}"
    state: present

- name: Create {{ vcenter.role_prefix }}-datastore_level role vc7
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: "{{ vcenter.role_prefix }}-datastore_level"
    local_privilege_ids: "{{ datastore_level | union(datastore_level_vc7) }}"
    state: present
  when: "vcenter_info.about_info.version.startswith('7.')"

- name: Create {{ vcenter.role_prefix }}-portgroup_level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: "{{ vcenter.role_prefix }}-portgroup_level"
    local_privilege_ids: "{{ portgroup_level }}"
    state: present

- name: Create {{ vcenter.role_prefix }}-folder_level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: "{{ vcenter.role_prefix }}-folder_level"
    local_privilege_ids: "{{ folder_level }}"
    state: present
  when:
    - openshift.installer_created_folder == False

- name: Create {{ vcenter.role_prefix }}-folder_level role vc7
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: "{{ vcenter.role_prefix }}-folder_level"
    local_privilege_ids: "{{ folder_level | union(folder_level_vc7) }}"
    state: present
  when:
    - openshift.installer_created_folder == False
    - vcenter_info.about_info.version.startswith('7.')

- name: Create {{ vcenter.role_prefix }}-datacenter_level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: "{{ vcenter.role_prefix }}-datacenter_level"
    local_privilege_ids: "{{ datacenter_level }}"
    state: present
  when:
    - openshift.installer_created_folder == True

- name: Create {{ vcenter.role_prefix }}-datacenter_level role vc7
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: "{{ vcenter.role_prefix }}-datacenter_level"
    local_privilege_ids: "{{ datacenter_level | union(datacenter_level_vc7) }}"
    state: present
  when:
    - openshift.installer_created_folder == True
    - vcenter_info.about_info.version.startswith('7.')
